# The URL the site will be built for
base_url = "https://iliazeus.lol"

compile_sass = true
generate_feeds = true

[markdown]
external_links_target_blank = true

[markdown.highlighting]
style = "class"
light_theme = "light-plus"
dark_theme = "red"

[extra]
# Put all your custom variables here
